#!/bin/bash
getid() { local file=$1; gvm-cli --gmp-username admin --gmp-password kali socket --socketpath /run/gvmd/gvmd.sock --xml '<get_reports/>' | xmlstarlet sel -t -v '//task/@id' | uniq > "$file"; }
saverp() { local line=$1; gvm-cli --gmp-username admin --gmp-password kali socket --socketpath /var/run/gvmd/gvmd.sock --xml "<get_results  filter='apply_overrides=0 min_qod=70 task_id=$line rows=1000 first=1 sort-reverse=severity' />" > rep/"$line"; }
send() { local file=$1; sendemail -f adamsperling535@gmail.com -t gameoverstron2077@gmail.com -u "Subject of the email" -m "OpenVas report send: bonjur" -a "$file2" -s smtp.gmail.com -o tls=yes -xu mail@gmail.com -xp "adam adam adam daam"; }

ss() {
    local file=$1
    getid "$file"
    cat "$file" | (while IFS= read -r line; do
        echo "$line"
        saverp "$line"
        file2="rep/$line"
        send "$file2"
    done)
}



ss "ids"

while true; do
    getid "ids2"
    seconds_in_month="30" #$((30 * 24 * 60 * 60))

	echo "Waiting for a month..."
	sleep "$seconds_in_month"
	echo "Done waiting."
    if ! diff -q "ids" "ids2" >/dev/null; then
        diff  ids ids2 | grep ">\|<" | tr -d ">< " > tmpids
        

        # Your code goes here
        echo "Executing your code because IDs are different."
        cat "tmpids" | (while IFS= read -r line; do
        echo "$line"
        saverp "$line"
        file2="rep/$line"
        send "$file2"
    	done)
        # Add your code here...
        
        
        # Save "ids2" as "ids"
        cp "ids2" "ids"
        #rm "ids2"
    else
        echo "IDs are the same. No action needed."
    fi;
done;
