#!/bin/bash

sudo gvm-start
echo "Sleeping be sure openvas is already running when continueing" >> /root/scripts/log.master
#sleep 180
sudo chmod 662  /var/run/gvmd/gvmd.sock

getid() { local file=$1; gvm-cli --gmp-username $GVMUSER --gmp-password $GVMPASWD socket --socketpath /run/gvmd/gvmd.sock --xml '<get_reports/>' | xmlstarlet sel -t -v '//task/@id' | uniq > "$file"; }
saverp() { local line=$1; gvm-cli --gmp-username $GVMUSER --gmp-password $GVMPASWD socket --socketpath /var/run/gvmd/gvmd.sock --xml "<get_results  filter='apply_overrides=0 min_qod=70 task_id=$line rows=1000 first=1 sort-reverse=severity' />" > "$rep/$line"; }
send() { local file=$1; sendemail -f "$FROMAIL" -t "$TOMAIL" -u "Report from Minion" -m "OpenVas report send: bonjur" -a "$file2" -s smtp.gmail.com -o tls=yes -xu "$FROMAIL" -xp "$APPKEY"; }

ss() {
    local file=$1
    getid "$file"
    cat "$file" | (while IFS= read -r line; do
        echo "$line"
        saverp "$line"
        file2="$rep/$line"
        send "$file2"
    done)
}

echo "all functions in" >> /root/scripts/log.master

rep="/root/scripts/reports/rep"
ids="/root/scripts/reports/ids"
ids2="/root/scripts/reports/ids2"
tmpids="/root/scripts/reports/tmpids"

echo "paths in $rep\t$id\t$ids2\t$tmpids" >> /root/scripts/log.master


echo "time check" >> /root/scripts/log.master
if [ ! -e timestamp ]; then
    d=$(date +%s)
    echo $d > timestamp
else
    d=$(cat timestamp)
fi

echo $d >> /root/scripts/log.master

dd=$(($d + 360))
echo $dd >> /root/scripts/log.master

e=$(date +%s)
if [ $e -gt $dd ]; then
	# do flip
	echo "flipping" >> /root/scripts/log.master

	#Start of Get Reports & send em
	if [ -e $rep ]; then
	echo "rep exist nothing to do" >> /root/scripts/log.master
	else 
	mkdir $rep
	echo "rep created" >> /root/scripts/log.master
	fi
	if [ -e "$ids" ]; then
		echo "Ids Exist" >> /root/scripts/log.master
		getid "$ids2"

	#    	seconds_in_month="1" #$((30 * 24 * 60 * 60))
	#	echo "Waiting for a month..."
	#	sleep "$seconds_in_month"
	#	echo "Done waiting."

	    if ! diff -q "$ids" "$ids2" >/dev/null; then
		diff  $ids $ids2 | grep ">\|<" | tr -d ">< " > "$tmpids"
		

		# Your code goes here
		echo "Executing your code because IDs are different." >> /root/scripts/log.master
		cat "$tmpids" | (while IFS= read -r line; do
		echo "$line"
		saverp "$line"
		file2="$rep/$line"
		send "$file2"
	    	done)
		# Add your code here...
		
		rm "$tmpids"
		# Save "ids2" as "ids"
		cp "$ids2" "$ids"
		rm "$ids2"
	    else
		echo "IDs are the same. No action needed." >> /root/scripts/log.master
	    fi;
	else
		echo "Ids not there starting firstime(should)" >> /root/scripts/log.master
		ss "$ids"
	fi

    echo $e > timestamp
else
sleep 60
fi

