#!/bin/bash
#in gmail set app password
sendemail -f mail@gmail.com \
    -t mail2@gmail.com \
    -u "Subject of the email" \
    -m "Body of the email" \
    -a "res" \
    -s smtp.gmail.com \
    -o tls=yes \
    -xu mail@gmail.com \
    -xp "APPKEY"
